### PR TITLE
ready build Editor

### PR DESCRIPTION
**Pull request by weekendkoder**
Hi.

It would be nice, if you can put ready-made nodeJS Editor into the release-section. Not everybody is conform with building such a editor with many tools. Thx.

### CODE REVIEW

**Comment by Megabyteceer** [comment]
Hi **weekendkoder** tahank you, can you axplain why do you need merge master in to dev?
Do you worry if any breaking changes will go to master directly?

This repo is upstream, and before push any changes here, we tes them on our private repo for month in real projects development. dev branch here on github was not used for a while.

**Comment by weekendkoder** [comment]
Hi. 

Sry for making the topic here, if its wrong, just move it, where it belongs / fits. I am in "pull requests" so therefore i added a
request question. I am not that familiar with github.

Your work on this Editor for PixiJS (thing-editor) looks very promising. So i wanted to give it a try. I already have some different editors, but they dont satisfy me for my tasks. I would like to have a download-ready build for my windows OS. This is why i was asking if you can provide an link to a build made in nodeJS for example.  Like you describe it here :

-mkdir game_editor_here
-cd game_editor_here
-git clone https://github.com/Megabyteceer/thing-editor.git
-git clone https://github.com/Megabyteceer/thing-project-example.git games/thing-project-example
-cd thing-editor
-npm i
-npm run-script create_env
-npm start

All these steps require different software be installed on my computer. And it would take me lot of time to get it work. So i hope it would be an easy job for you, to provide a ready-to-start-version of the "thing-editor" in the release-section, i can try out. Thank you.

**Comment by Megabyteceer** [comment]
Thanks i got it. We will try to find easy way for installing to all platforms. Thank you.

**Comment by weekendkoder** [comment]
Super. It would really be great, if you can manage it. Many game-makers out there are just more visual, than technical. This way, your software gets a bigger userbase, in my opinion. The more Feedback you get, the better you can optimize your work. Thank you for making it happen.

**Pull request merged**
